site_name: Example
watch: [mkdocs.yml, README.md, src]

nav:
  - Home: index.md
  - API reference: reference/

theme:
  name: material
  features:
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.code.annotate
    - navigation.indexes
    - navigation.footer
    - navigation.sections
    - navigation.expand
    - toc.follow

plugins:
  - autorefs
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_nav.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: "numpy"
            heading_level: 1
            extensions:
              - griffe_fieldz
